---
all:
  children:
    openclaw_servers:
      hosts:
        helios:
          ansible_host: "{{ helios_ip }}"
          ansible_python_interpreter: /usr/bin/python3
          openclaw_user: "{{ openclaw_default_user }}"
          debian_user: "{{ openclaw_default_user }}"
          mise_user: "{{ openclaw_default_user }}"
          hostname: helios
          discord_bot_token: "{{ helios_bot_token }}"
          tailscale_authkey: "{{ helios_tailscale_authkey }}"
    claude_servers:
      hosts:
        athena:
          ansible_host: "{{ athena_ip }}"
          ansible_python_interpreter: /usr/bin/python3
          mise_user: "{{ claude_default_user }}"
          debian_user: "{{ claude_default_user }}"
          claude_user: "{{ claude_default_user }}"
          docker_user: "{{ claude_default_user }}"
          hostname: athena
          git_user_name: "{{ athena_git_user_name }}"
          git_user_email: "{{ athena_git_user_email }}"
          discord_bot_token: "{{ athena_bot_token }}"
          claude_working_directory: /home/{{ claude_default_user }}/workspace
